# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offender_ip', models.CharField(max_length=16, verbose_name='Attacker IP')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('user', models.CharField(max_length=30, verbose_name='Reporting User')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('action', models.IntegerField(verbose_name='Action')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist_IP',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='IP')),
                ('blacklist_duration', models.IntegerField(default=None, null=True, verbose_name='Blacklist Duration')),
                ('reason', models.TextField(default=None, null=True, verbose_name='Reason')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offender_ip', models.CharField(max_length=16, verbose_name='IP')),
                ('target_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Target IP')),
                ('time', models.DateTimeField()),
                ('protocol', models.CharField(max_length=3, verbose_name='Protocol')),
                ('port', models.CharField(max_length=11, verbose_name='Port')),
                ('hostname', models.CharField(default=None, max_length=50, null=True, verbose_name='Hostname')),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='IP_Upload_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('uploadDate', models.DateField()),
                ('content', models.FileField(upload_to='/opt/uploads/fail2ban/')),
                ('uploadedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offenders',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='IP')),
                ('strikes', models.IntegerField(default=1, verbose_name='Strikes')),
                ('total_strikes', models.IntegerField(default=1, verbose_name='Overall Strikes')),
                ('last_offense_date', models.DateTimeField(db_index=True, verbose_name='Last Offense')),
                ('last_offense_target', models.CharField(default=None, max_length=15, null=True, verbose_name='Last Target')),
                ('blacklisted', models.BooleanField(db_index=True, default=False, verbose_name='Blacklisted')),
                ('last_blacklisted_date', models.DateTimeField(default=None, null=True, verbose_name='Last Blacklisted')),
                ('last_blacklist_remove_date', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='Last Removal Date')),
                ('blacklist_duration', models.IntegerField(default=None, null=True, verbose_name='Blacklist Duration')),
                ('blacklist_removal_date', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='Removal Date')),
                ('subnet_mask', models.CharField(db_index=True, default='/32', max_length=3, verbose_name='Subnet')),
                ('tag', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('ip', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='IP')),
                ('date', models.DateTimeField(default=None, null=True, verbose_name='Date')),
                ('user', models.CharField(default='f2b admin', max_length=255, verbose_name='Reporting User')),
                ('reason', models.TextField(default=None, null=True, verbose_name='Reason')),
            ],
        ),
    ]
